// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/notes/data/models/note_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 940365444142600783),
    name: 'NoteModel',
    lastPropertyId: const obx_int.IdUid(11, 8297143530793730413),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7617668262321852073),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5289103376180553297),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 6536007773405949759),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9092955234181501632),
        name: 'title',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 4533480706276447797),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1338719570332931673),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8121387899526550199),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3789021673161051343),
        name: 'updatedAt',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(3, 8195120955829410814),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3242500718914919009),
        name: 'plainText',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7957471537971335329),
        name: 'previewText',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5161078860881858672),
        name: 'height',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5972503054547634601),
        name: 'isPinned',
        type: 1,
        flags: 8,
        indexId: const obx_int.IdUid(4, 3439249776280742230),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 940365444142600783),
    lastIndexId: const obx_int.IdUid(4, 3439249776280742230),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [8297143530793730413],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    NoteModel: obx_int.EntityDefinition<NoteModel>(
      model: _entities[0],
      toOneRelations: (NoteModel object) => [],
      toManyRelations: (NoteModel object) => {},
      getId: (NoteModel object) => object.obxId,
      setId: (NoteModel object, int id) {
        object.obxId = id;
      },
      objectToFB: (NoteModel object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final titleOffset = fbb.writeString(object.title);
        final contentOffset = fbb.writeString(object.content);
        final plainTextOffset = fbb.writeString(object.plainText);
        final previewTextOffset = fbb.writeString(object.previewText);
        fbb.startTable(12);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, contentOffset);
        fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(5, object.updatedAt.millisecondsSinceEpoch);
        fbb.addOffset(6, plainTextOffset);
        fbb.addOffset(7, previewTextOffset);
        fbb.addFloat64(8, object.height);
        fbb.addBool(9, object.isPinned);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final plainTextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final previewTextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final heightParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final isPinnedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final object = NoteModel(
          obxId: obxIdParam,
          id: idParam,
          title: titleParam,
          content: contentParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          plainText: plainTextParam,
          previewText: previewTextParam,
          height: heightParam,
          isPinned: isPinnedParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [NoteModel] entity fields to define ObjectBox queries.
class NoteModel_ {
  /// See [NoteModel.obxId].
  static final obxId = obx.QueryIntegerProperty<NoteModel>(
    _entities[0].properties[0],
  );

  /// See [NoteModel.id].
  static final id = obx.QueryStringProperty<NoteModel>(
    _entities[0].properties[1],
  );

  /// See [NoteModel.title].
  static final title = obx.QueryStringProperty<NoteModel>(
    _entities[0].properties[2],
  );

  /// See [NoteModel.content].
  static final content = obx.QueryStringProperty<NoteModel>(
    _entities[0].properties[3],
  );

  /// See [NoteModel.createdAt].
  static final createdAt = obx.QueryDateProperty<NoteModel>(
    _entities[0].properties[4],
  );

  /// See [NoteModel.updatedAt].
  static final updatedAt = obx.QueryDateProperty<NoteModel>(
    _entities[0].properties[5],
  );

  /// See [NoteModel.plainText].
  static final plainText = obx.QueryStringProperty<NoteModel>(
    _entities[0].properties[6],
  );

  /// See [NoteModel.previewText].
  static final previewText = obx.QueryStringProperty<NoteModel>(
    _entities[0].properties[7],
  );

  /// See [NoteModel.height].
  static final height = obx.QueryDoubleProperty<NoteModel>(
    _entities[0].properties[8],
  );

  /// See [NoteModel.isPinned].
  static final isPinned = obx.QueryBooleanProperty<NoteModel>(
    _entities[0].properties[9],
  );
}
